# ============================================================
# DESIGN SKILLS MASTER GUIDE
# Covers: Graphic Design | Motion Design | Photos & Photo Selection |
#         Professional Presentations
# Source: Claude AI + GitHub Design Roadmap Research
# Most-Wanted Skills: Based on 2024-2025 Job Market Research
# Author: Generated by Claude (Anthropic) for badrburshaid-netizen
# ============================================================

import json
from datetime import datetime

# ─────────────────────────────────────────────────────────────
# 1. GRAPHIC DESIGN SKILLS
# (Enhanced with most in-demand / wanted skills for 2024-2025)
# ─────────────────────────────────────────────────────────────
GRAPHIC_DESIGN_SKILLS = {
    "Foundations": [
        "Color Theory (hue, saturation, value, color harmony)",
        "Typography (typefaces, hierarchy, kerning, leading, tracking)",
        "Layout & Composition (grid systems, rule of thirds, whitespace)",
        "Visual Hierarchy (size, contrast, alignment, repetition)",
        "Shape, Form & Space (positive/negative space, Gestalt principles)",
        "Balance & Contrast (symmetrical vs asymmetrical design)",
        "Design Systems & Component-Based Thinking",  # MOST WANTED
        "Accessibility & Inclusive Design (WCAG standards)",  # MOST WANTED
    ],
    "Technical_Software": [
        "Adobe Illustrator - vector graphics & logo design",
        "Adobe Photoshop - image editing & compositing",
        "Adobe InDesign - layout & print production",
        "Figma - UI/UX prototyping & collaborative design",  # #1 MOST WANTED
        "Canva - fast template-based design",
        "Affinity Designer / Publisher - budget-friendly alternatives",
        "CorelDRAW - professional vector & print design",
        "Sketch - macOS UI/UX design tool",
        "Adobe Express - quick social content creation",  # MOST WANTED
        "Procreate - digital illustration on iPad",  # MOST WANTED
        "Midjourney / Adobe Firefly - AI-assisted design",  # MOST WANTED
        "Framer - interactive web design & prototyping",  # MOST WANTED
    ],
    "Branding_Identity": [
        "Logo design principles (scalability, memorability, versatility)",
        "Brand identity systems (color palette, fonts, tone)",
        "Style guide creation",
        "Iconography design",
        "Packaging design",
        "Stationery & corporate collateral design",
        "Motion branding & animated logos",  # MOST WANTED
        "Brand strategy & positioning",  # MOST WANTED
        "Design token systems (for digital brand consistency)",  # MOST WANTED
    ],
    "Print_Production": [
        "CMYK vs RGB color modes",
        "Bleed, trim, and safe zones",
        "DPI / PPI resolution requirements",
        "Pre-press preparation & file export",
        "Vector vs raster file formats (SVG, EPS, PDF, PNG, JPG)",
    ],
    "Digital_Design": [
        "Responsive & adaptive design principles",
        "UI/UX fundamentals (wireframing, prototyping, user flows)",
        "Web design basics (HTML/CSS awareness)",
        "Motion graphics (After Effects, Lottie)",
        "Social media graphic standards (sizes, aspect ratios)",
        "Email marketing design",
        "App icon & mobile UI design",  # MOST WANTED
        "3D design basics (Blender, Cinema 4D, Spline)",  # MOST WANTED
        "AR/VR design concepts (immersive UI/UX)",  # MOST WANTED
        "Interactive & scroll-based animations for web",  # MOST WANTED
        "Generative & parametric design (AI-driven visuals)",  # MOST WANTED
    ],
    "AI_Powered_Design_Skills": [  # NEW MOST WANTED CATEGORY
        "Prompt engineering for image generation (Midjourney, DALL-E, Firefly)",
        "AI-assisted image editing (Adobe Generative Fill, Photoshop AI)",
        "AI background removal & upscaling (Remove.bg, Topaz)",
        "AI-driven layout tools (Framer AI, Galileo AI, Uizard)",
        "AI color palette generators (Coolors, Adobe Color AI)",
        "AI typography pairing tools (Fontjoy, Typewolf)",
        "Automation & batch design with AI (Canva AI, Figma plugins)",
    ],
    "Soft_Creative_Skills": [
        "Creative problem solving & ideation",
        "Client communication & brief interpretation",
        "Design critique & feedback incorporation",
        "Time management & meeting deadlines",
        "Portfolio building & presentation",
        "Trend awareness & continuous learning",
        "Cross-functional collaboration (with developers & marketers)",  # MOST WANTED
        "Design thinking & user-centered process",  # MOST WANTED
    ],
}

# ─────────────────────────────────────────────────────────────
# 2. MOTION DESIGN & GRAPHIC DESIGN MOTION SKILLS
# (Most In-Demand for 2024-2025 — Based on Job Listings & Industry Research)
# ─────────────────────────────────────────────────────────────
MOTION_DESIGN_SKILLS = {
    "Motion_Design_Foundations": [
        "12 Principles of Animation (squash & stretch, anticipation, timing, etc.)",
        "Easing & Interpolation (ease-in, ease-out, cubic bezier curves)",
        "Storyboarding & Animatics for motion projects",
        "Timing, Pacing & Rhythm in animation",
        "Frame rate fundamentals (24fps, 30fps, 60fps)",
        "Motion paths & trajectory control",
        "Layer-based vs node-based animation workflows",
        "Visual storytelling through motion",
    ],
    "Core_Motion_Software": [  # MOST WANTED
        "Adobe After Effects - industry-standard motion graphics & VFX",  # #1 MOST WANTED
        "Adobe Premiere Pro - video editing & timeline work",
        "Cinema 4D (C4D) - 3D motion design & MoGraph module",  # TOP DEMAND
        "Blender - free & open-source 3D animation & motion",  # TOP DEMAND
        "DaVinci Resolve - color grading + Fusion for compositing",
        "Apple Motion - macOS-native motion graphics",
        "Cavalry - procedural motion design tool",
        "HitFilm Express - free compositing & VFX",
        "Rive - real-time interactive animation for apps & web",  # MOST WANTED
        "Lottie / LottieFiles - lightweight JSON animations for web & mobile",  # MOST WANTED
        "Spline - 3D design & animation for web",  # MOST WANTED
        "Jitter - fast animated social content creation",
    ],
    "After_Effects_Specific_Skills": [  # MOST WANTED
        "Keyframe animation & graph editor mastery",
        "Shape layers & path-based animation",
        "Text animation & kinetic typography",
        "Mask & track matte techniques",
        "Motion blur & depth of field effects",
        "Expressions (JavaScript-based automation in AE)",  # TOP DEMAND
        "Null objects & parenting hierarchy",
        "3D layers, cameras & lights in After Effects",
        "Compositing with green screen / chroma key",
        "Plugin ecosystem: Video Copilot, Trapcode Suite, Motion Bro",
        "Rendering & output: Media Encoder, ProRes, H.264 settings",
        "Pre-composing & nested composition structure",
    ],
    "UI_UX_Motion_Design": [  # MOST WANTED
        "Micro-interactions & UI animation design",
        "Transition design (screen-to-screen, element-to-element)",
        "Scroll-triggered animations (GSAP, Framer Motion)",
        "Figma Smart Animate & Prototype animations",
        "Rive for interactive UI states & real-time animations",
        "CSS animations & keyframes for web",
        "Framer - interactive motion prototyping for web",
        "Principle App - interactive UI animations",
        "Loading & skeleton screen animations",
        "Haptic & audio feedback design pairing with motion",
    ],
    "3D_Motion_Design": [  # MOST WANTED
        "3D modeling basics (poly modeling, subdivision)",
        "Cinema 4D MoGraph (cloners, effectors, fields)",  # TOP DEMAND
        "Blender rendering (Cycles, EEVEE)",
        "Redshift / Arnold / Octane rendering engines",
        "Procedural texturing & shading (Substance Painter)",
        "Character rigging & skinning basics",
        "Particle systems & simulations (fluids, cloth, smoke)",
        "Camera animation & virtual cinematography",
        "3D typography & logo animations",
        "Environment design & virtual set extension",
        "Spline for 3D web experiences",
    ],
    "Social_Content_Motion": [  # MOST WANTED
        "Vertical video design (9:16 for Reels, TikTok, Shorts)",
        "Animated social media posts & stories",
        "Lower thirds & broadcast graphics",
        "Animated infographics & data visualization",
        "GIF creation & optimization (Photoshop, Ezgif)",
        "Short-form video hooks & motion CTAs",
        "Template-based motion in CapCut / Adobe Express",
        "Brand-consistent motion style guides",
    ],
    "Visual_Effects_VFX": [
        "Motion tracking & camera tracking",
        "Rotoscoping & masking",
        "Color grading for video (DaVinci Resolve)",
        "Green screen / chroma key compositing",
        "Particle effects & simulations",
        "Title design & broadcast package creation",
        "Sound design basics for motion (sync audio to visuals)",
        "VFX compositing pipelines",
    ],
    "Web_Interactive_Motion": [  # MOST WANTED
        "CSS animations & transitions",
        "GSAP (GreenSock Animation Platform) - professional web animation",  # TOP DEMAND
        "Framer Motion - React-based animation library",  # MOST WANTED
        "Lottie integration in web & mobile apps",
        "WebGL & Three.js basics for 3D web",
        "Scroll-based storytelling & parallax effects",
        "SVG animation (SMIL, CSS, JavaScript)",
        "Canvas-based animations",
        "p5.js - creative coding & generative motion",
    ],
    "Motion_AI_Tools": [  # MOST WANTED (Emerging)
        "Runway ML - AI video generation & editing",  # TOP DEMAND
        "Pika Labs - text-to-video AI animation",
        "Sora (OpenAI) - AI video generation",
        "Adobe Firefly Video - AI-powered video generation",
        "Kling AI / Stable Video Diffusion - AI motion creation",
        "ElevenLabs + D-ID - AI avatar & voice animation",
        "Kaiber AI - artistic motion & music visualization",
        "AI-assisted rotoscoping & object removal",
    ],
    "Motion_Design_Workflow": [
        "Style frames & motion mood boards",
        "Motion style guides & design systems",
        "Asset organization (libraries, templates, presets)",
        "Collaboration with developers (Lottie handoff, CSS specs)",
        "Client presentation of motion concepts",
        "Rendering optimization & compression best practices",
        "Version control for motion projects",
        "Motion brief interpretation & concept development",
    ],
    "Most_Wanted_Motion_Skills_Summary": [  # KEY INSIGHT SECTION
        "[#1] After Effects mastery - required in 85%+ of motion job listings",
        "[#2] Figma + Smart Animate - UI motion for product design roles",
        "[#3] Cinema 4D / Blender - 3D motion increasingly expected",
        "[#4] GSAP / Framer Motion - web animation for digital agencies",
        "[#5] Lottie / Rive - lightweight interactive animation for apps",
        "[#6] Runway ML / AI video tools - emerging but growing fast",
        "[#7] Social media motion (Reels/TikTok format) - brand & agency demand",
        "[#8] Kinetic typography - high demand for ads & social content",
        "[#9] AE Expressions (JavaScript) - separates mid from senior level",
        "[#10] Brand motion systems - style guides with animated logos/transitions",
    ],
}

# ─────────────────────────────────────────────────────────────
# 3. PHOTOGRAPHY & PHOTO SELECTION FOR DESIGN SKILLS
# ─────────────────────────────────────────────────────────────
PHOTO_SKILLS = {
    "Photography_Fundamentals": [
        "Exposure triangle (aperture, shutter speed, ISO)",
        "Lighting techniques (natural, studio, diffused, dramatic)",
        "Composition rules (rule of thirds, leading lines, framing)",
        "Depth of field control",
        "White balance & color temperature",
        "Focus & sharpness techniques",
    ],
    "Photo_Editing": [
        "Adobe Lightroom - color grading, batch editing, RAW processing",
        "Adobe Photoshop - retouching, compositing, masking",
        "Capture One - professional color & tethering",
        "Luminar AI / Neo - AI-powered enhancements",
        "Color correction & tone curve adjustment",
        "Dodging, burning & frequency separation retouching",
    ],
    "Selecting_Photos_for_Design": [
        "Visual relevance - does the image support the message/brand?",
        "Technical quality - resolution, sharpness, noise-free (min 300 DPI for print)",
        "Composition suitability - space for text overlay (negative space)",
        "Color harmony - image palette matches brand colors",
        "Emotional impact - conveys the right mood and tone",
        "Authenticity - avoid overly staged or generic stock images",
        "Subject focus - clear focal point without clutter",
        "Licensing & rights - royalty-free, Creative Commons, or licensed",
        "Consistency - visual style matches other images in the project",
        "Scalability - image works well cropped or at different sizes",
    ],
    "Stock_Photo_Platforms": [
        "Unsplash - free, high-quality creative commons",
        "Pexels - free stock photos and videos",
        "Shutterstock - premium licensed stock",
        "Adobe Stock - integrated with Creative Cloud",
        "Getty Images - premium editorial & commercial",
        "iStock - affordable Getty-owned option",
        "Pixabay - free with broad license",
        "Freepik - vectors + photos + mockups",
    ],
    "Advanced_Photo_Skills": [
        "Image masking & compositing",
        "Background removal (manual & AI tools)",
        "Photo manipulation & double exposure",
        "Color palette extraction from images",
        "AI upscaling (Topaz Gigapixel, Adobe Super Resolution)",
        "Smart object usage in Photoshop",
        "HDR photography basics",
    ],
}

# ─────────────────────────────────────────────────────────────
# 4. PROFESSIONAL PRESENTATION SKILLS
# ─────────────────────────────────────────────────────────────
PRESENTATION_SKILLS = {
    "Design_Principles_for_Slides": [
        "One idea per slide rule",
        "Consistent color palette & typography across all slides",
        "Use of whitespace to avoid visual clutter",
        "Data visualization (charts, infographics, graphs)",
        "Icon usage for visual communication",
        "Slide master & template creation",
        "Image-text balance",
        "Contrast for readability (dark vs light backgrounds)",
    ],
    "Software_Tools": [
        "Microsoft PowerPoint - industry standard, robust animations",
        "Google Slides - collaborative, cloud-based",
        "Apple Keynote - sleek, macOS-optimized",
        "Canva Presentations - template-rich, beginner-friendly",
        "Prezi - zooming, non-linear narrative presentations",
        "Beautiful.ai - AI-powered auto-layout",
        "Pitch - modern, collaborative deck tool",
        "Gamma - AI presentation generator",
    ],
    "Content_Structure": [
        "Story arc: Problem > Solution > Proof > Call to Action",
        "Executive summary slide",
        "Table of contents / agenda slide",
        "Clear section dividers",
        "Effective use of bullet points (max 3-5 per slide)",
        "Speaker notes writing",
        "Compelling headline slides",
        "Strong closing / CTA slide",
    ],
    "Visual_Enhancement": [
        "Custom illustration & iconography use",
        "Animated transitions (subtle, purposeful)",
        "Video & GIF embedding",
        "Mockup & device frame integration",
        "Custom chart and graph design",
        "Branded slide templates",
        "Smart art & diagram creation",
    ],
    "Delivery_Communication": [
        "Public speaking confidence",
        "Eye contact & body language",
        "Pacing & pause technique",
        "Audience engagement strategies",
        "Handling Q&A sessions",
        "Virtual presentation skills (Zoom, Teams)",
        "Rehearsal & timing management",
        "Storytelling & narrative design",
    ],
    "Professional_Standards": [
        "Font size minimum: 24pt body, 36pt+ headlines",
        "Max 6 words per bullet point",
        "Color accessibility (WCAG contrast ratios)",
        "PDF export for universal sharing",
        "16:9 widescreen format as default",
        "Consistent margins & alignment",
        "Company branding compliance",
    ],
}

# ─────────────────────────────────────────────────────────────
# DISPLAY FUNCTIONS
# ─────────────────────────────────────────────────────────────

def print_section(title, skills_dict, emoji=""):
    line = "=" * 65
    print(f"\n{line}")
    print(f" {emoji} {title.upper()}")
    print(line)
    for category, skills in skills_dict.items():
        cat_display = category.replace("_", " ")
        print(f"\n > {cat_display}")
        print(f" {'-' * 50}")
        for i, skill in enumerate(skills, 1):
            print(f"   {i:02d}. {skill}")

def export_to_json(filename="design_skills.json"):
    data = {
        "generated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "source": "Claude AI + GitHub Design Roadmap Research",
        "repo": "https://github.com/badrburshaid-netizen/design-skills-claude",
        "sections": {
            "graphic_design": GRAPHIC_DESIGN_SKILLS,
            "motion_design": MOTION_DESIGN_SKILLS,
            "photography_and_photo_selection": PHOTO_SKILLS,
            "professional_presentations": PRESENTATION_SKILLS,
        }
    }
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"\n[OK] Skills exported to '{filename}'")

def export_to_txt(filename="design_skills.txt"):
    lines = []
    lines.append("DESIGN SKILLS MASTER GUIDE")
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("Source: Claude AI + GitHub Design Roadmap Research")
    lines.append("Repo: https://github.com/badrburshaid-netizen/design-skills-claude")
    lines.append("=" * 65)
    all_sections = [
        ("GRAPHIC DESIGN SKILLS", GRAPHIC_DESIGN_SKILLS),
        ("MOTION DESIGN SKILLS", MOTION_DESIGN_SKILLS),
        ("PHOTOGRAPHY & PHOTO SELECTION SKILLS", PHOTO_SKILLS),
        ("PROFESSIONAL PRESENTATION SKILLS", PRESENTATION_SKILLS),
    ]
    for title, skills_dict in all_sections:
        lines.append(f"\n\n{'=' * 65}")
        lines.append(f" {title}")
        lines.append("=" * 65)
        for category, skills in skills_dict.items():
            lines.append(f"\n  {category.replace('_', ' ')}")
            lines.append("  " + "-" * 45)
            for i, skill in enumerate(skills, 1):
                lines.append(f"    {i:02d}. {skill}")
    with open(filename, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[OK] Skills exported to '{filename}'")

def export_to_markdown(filename="SKILLS.md"):
    lines = []
    lines.append("# Design Skills Master Guide")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} ")
    lines.append("**Source:** Claude AI + GitHub Design Roadmap Research ")
    lines.append("**Repo:** [design-skills-claude](https://github.com/badrburshaid-netizen/design-skills-claude)\n")
    all_sections = [
        ("Graphic Design Skills", GRAPHIC_DESIGN_SKILLS),
        ("Motion Design Skills", MOTION_DESIGN_SKILLS),
        ("Photography & Photo Selection Skills", PHOTO_SKILLS),
        ("Professional Presentation Skills", PRESENTATION_SKILLS),
    ]
    for title, skills_dict in all_sections:
        lines.append(f"\n## {title}\n")
        for category, skills in skills_dict.items():
            lines.append(f"### {category.replace('_', ' ')}\n")
            for skill in skills:
                lines.append(f"- {skill}")
            lines.append("")
    with open(filename, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[OK] Skills exported to '{filename}'")

def count_total_skills():
    total = 0
    for d in [GRAPHIC_DESIGN_SKILLS, MOTION_DESIGN_SKILLS, PHOTO_SKILLS, PRESENTATION_SKILLS]:
        for skills in d.values():
            total += len(skills)
    return total

# ─────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("\n" + "#" * 65)
    print(" DESIGN SKILLS MASTER GUIDE")
    print(" Source: Claude AI + GitHub Roadmap Research")
    print(" Repo: github.com/badrburshaid-netizen/design-skills-claude")
    print(" Generated:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    print("#" * 65)

    print_section("Graphic Design Skills", GRAPHIC_DESIGN_SKILLS, "[DESIGN]")
    print_section("Motion Design Skills", MOTION_DESIGN_SKILLS, "[MOTION]")
    print_section("Photography & Photo Selection Skills", PHOTO_SKILLS, "[PHOTO]")
    print_section("Professional Presentation Skills", PRESENTATION_SKILLS, "[SLIDES]")

    print(f"\n\n{'=' * 65}")
    print(f" TOTAL SKILLS CATALOGUED: {count_total_skills()}")
    print(f"{'=' * 65}")

    export_to_json("design_skills.json")
    export_to_txt("design_skills.txt")
    export_to_markdown("SKILLS.md")

    print("\n[DONE] Run this script to view and export all design skills.\n")
