# ============================================================
#  DESIGN SKILLS MASTER GUIDE
#  Covers: Graphic Design | Photos & Photo Selection |
#          Professional Presentations
#  Source: Claude AI + GitHub Design Roadmap Research
#  Author: Generated by Claude (Anthropic) for badrburshaid-netizen
# ============================================================

import json
from datetime import datetime

# ─────────────────────────────────────────────────────────────
# 1. GRAPHIC DESIGN SKILLS
# ─────────────────────────────────────────────────────────────
GRAPHIC_DESIGN_SKILLS = {
    "Foundations": [
        "Color Theory (hue, saturation, value, color harmony)",
        "Typography (typefaces, hierarchy, kerning, leading, tracking)",
        "Layout & Composition (grid systems, rule of thirds, whitespace)",
        "Visual Hierarchy (size, contrast, alignment, repetition)",
        "Shape, Form & Space (positive/negative space, Gestalt principles)",
        "Balance & Contrast (symmetrical vs asymmetrical design)",
    ],
    "Technical_Software": [
        "Adobe Illustrator - vector graphics & logo design",
        "Adobe Photoshop - image editing & compositing",
        "Adobe InDesign - layout & print production",
        "Figma - UI/UX prototyping & collaborative design",
        "Canva - fast template-based design",
        "Affinity Designer / Publisher - budget-friendly alternatives",
        "CorelDRAW - professional vector & print design",
        "Sketch - macOS UI/UX design tool",
    ],
    "Branding_Identity": [
        "Logo design principles (scalability, memorability, versatility)",
        "Brand identity systems (color palette, fonts, tone)",
        "Style guide creation",
        "Iconography design",
        "Packaging design",
        "Stationery & corporate collateral design",
    ],
    "Print_Production": [
        "CMYK vs RGB color modes",
        "Bleed, trim, and safe zones",
        "DPI / PPI resolution requirements",
        "Pre-press preparation & file export",
        "Vector vs raster file formats (SVG, EPS, PDF, PNG, JPG)",
    ],
    "Digital_Design": [
        "Responsive & adaptive design principles",
        "UI/UX fundamentals (wireframing, prototyping, user flows)",
        "Web design basics (HTML/CSS awareness)",
        "Motion graphics (After Effects, Lottie)",
        "Social media graphic standards (sizes, aspect ratios)",
        "Email marketing design",
    ],
    "Soft_Creative_Skills": [
        "Creative problem solving & ideation",
        "Client communication & brief interpretation",
        "Design critique & feedback incorporation",
        "Time management & meeting deadlines",
        "Portfolio building & presentation",
        "Trend awareness & continuous learning",
    ],
}

# ─────────────────────────────────────────────────────────────
# 2. PHOTOGRAPHY & PHOTO SELECTION FOR DESIGN SKILLS
# ─────────────────────────────────────────────────────────────
PHOTO_SKILLS = {
    "Photography_Fundamentals": [
        "Exposure triangle (aperture, shutter speed, ISO)",
        "Lighting techniques (natural, studio, diffused, dramatic)",
        "Composition rules (rule of thirds, leading lines, framing)",
        "Depth of field control",
        "White balance & color temperature",
        "Focus & sharpness techniques",
    ],
    "Photo_Editing": [
        "Adobe Lightroom - color grading, batch editing, RAW processing",
        "Adobe Photoshop - retouching, compositing, masking",
        "Capture One - professional color & tethering",
        "Luminar AI / Neo - AI-powered enhancements",
        "Color correction & tone curve adjustment",
        "Dodging, burning & frequency separation retouching",
    ],
    "Selecting_Photos_for_Design": [
        "Visual relevance - does the image support the message/brand?",
        "Technical quality - resolution, sharpness, noise-free (min 300 DPI for print)",
        "Composition suitability - space for text overlay (negative space)",
        "Color harmony - image palette matches brand colors",
        "Emotional impact - conveys the right mood and tone",
        "Authenticity - avoid overly staged or generic stock images",
        "Subject focus - clear focal point without clutter",
        "Licensing & rights - royalty-free, Creative Commons, or licensed",
        "Consistency - visual style matches other images in the project",
        "Scalability - image works well cropped or at different sizes",
    ],
    "Stock_Photo_Platforms": [
        "Unsplash - free, high-quality creative commons",
        "Pexels - free stock photos and videos",
        "Shutterstock - premium licensed stock",
        "Adobe Stock - integrated with Creative Cloud",
        "Getty Images - premium editorial & commercial",
        "iStock - affordable Getty-owned option",
        "Pixabay - free with broad license",
        "Freepik - vectors + photos + mockups",
    ],
    "Advanced_Photo_Skills": [
        "Image masking & compositing",
        "Background removal (manual & AI tools)",
        "Photo manipulation & double exposure",
        "Color palette extraction from images",
        "AI upscaling (Topaz Gigapixel, Adobe Super Resolution)",
        "Smart object usage in Photoshop",
        "HDR photography basics",
    ],
}

# ─────────────────────────────────────────────────────────────
# 3. PROFESSIONAL PRESENTATION SKILLS
# ─────────────────────────────────────────────────────────────
PRESENTATION_SKILLS = {
    "Design_Principles_for_Slides": [
        "One idea per slide rule",
        "Consistent color palette & typography across all slides",
        "Use of whitespace to avoid visual clutter",
        "Data visualization (charts, infographics, graphs)",
        "Icon usage for visual communication",
        "Slide master & template creation",
        "Image-text balance",
        "Contrast for readability (dark vs light backgrounds)",
    ],
    "Software_Tools": [
        "Microsoft PowerPoint - industry standard, robust animations",
        "Google Slides - collaborative, cloud-based",
        "Apple Keynote - sleek, macOS-optimized",
        "Canva Presentations - template-rich, beginner-friendly",
        "Prezi - zooming, non-linear narrative presentations",
        "Beautiful.ai - AI-powered auto-layout",
        "Pitch - modern, collaborative deck tool",
        "Gamma - AI presentation generator",
    ],
    "Content_Structure": [
        "Story arc: Problem > Solution > Proof > Call to Action",
        "Executive summary slide",
        "Table of contents / agenda slide",
        "Clear section dividers",
        "Effective use of bullet points (max 3-5 per slide)",
        "Speaker notes writing",
        "Compelling headline slides",
        "Strong closing / CTA slide",
    ],
    "Visual_Enhancement": [
        "Custom illustration & iconography use",
        "Animated transitions (subtle, purposeful)",
        "Video & GIF embedding",
        "Mockup & device frame integration",
        "Custom chart and graph design",
        "Branded slide templates",
        "Smart art & diagram creation",
    ],
    "Delivery_Communication": [
        "Public speaking confidence",
        "Eye contact & body language",
        "Pacing & pause technique",
        "Audience engagement strategies",
        "Handling Q&A sessions",
        "Virtual presentation skills (Zoom, Teams)",
        "Rehearsal & timing management",
        "Storytelling & narrative design",
    ],
    "Professional_Standards": [
        "Font size minimum: 24pt body, 36pt+ headlines",
        "Max 6 words per bullet point",
        "Color accessibility (WCAG contrast ratios)",
        "PDF export for universal sharing",
        "16:9 widescreen format as default",
        "Consistent margins & alignment",
        "Company branding compliance",
    ],
}

# ─────────────────────────────────────────────────────────────
# DISPLAY FUNCTIONS
# ─────────────────────────────────────────────────────────────

def print_section(title, skills_dict, emoji=""):
    line = "=" * 65
    print(f"\n{line}")
    print(f"  {emoji}  {title.upper()}")
    print(line)
    for category, skills in skills_dict.items():
        cat_display = category.replace("_", " ")
        print(f"\n  > {cat_display}")
        print(f"  {'-' * 50}")
        for i, skill in enumerate(skills, 1):
            print(f"    {i:02d}. {skill}")

def export_to_json(filename="design_skills.json"):
    data = {
        "generated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "source": "Claude AI + GitHub Design Roadmap Research",
        "repo": "https://github.com/badrburshaid-netizen/design-skills-claude",
        "sections": {
            "graphic_design": GRAPHIC_DESIGN_SKILLS,
            "photography_and_photo_selection": PHOTO_SKILLS,
            "professional_presentations": PRESENTATION_SKILLS,
        }
    }
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"\n[OK] Skills exported to '{filename}'")

def export_to_txt(filename="design_skills.txt"):
    lines = []
    lines.append("DESIGN SKILLS MASTER GUIDE")
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("Source: Claude AI + GitHub Design Roadmap Research")
    lines.append("Repo: https://github.com/badrburshaid-netizen/design-skills-claude")
    lines.append("=" * 65)
    all_sections = [
        ("GRAPHIC DESIGN SKILLS", GRAPHIC_DESIGN_SKILLS),
        ("PHOTOGRAPHY & PHOTO SELECTION SKILLS", PHOTO_SKILLS),
        ("PROFESSIONAL PRESENTATION SKILLS", PRESENTATION_SKILLS),
    ]
    for title, skills_dict in all_sections:
        lines.append(f"\n\n{'=' * 65}")
        lines.append(f"  {title}")
        lines.append("=" * 65)
        for category, skills in skills_dict.items():
            lines.append(f"\n  {category.replace('_', ' ')}")
            lines.append("  " + "-" * 45)
            for i, skill in enumerate(skills, 1):
                lines.append(f"    {i:02d}. {skill}")
    with open(filename, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[OK] Skills exported to '{filename}'")

def export_to_markdown(filename="SKILLS.md"):
    lines = []
    lines.append("# Design Skills Master Guide")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  ")
    lines.append("**Source:** Claude AI + GitHub Design Roadmap Research  ")
    lines.append("**Repo:** [design-skills-claude](https://github.com/badrburshaid-netizen/design-skills-claude)\n")
    all_sections = [
        ("Graphic Design Skills", GRAPHIC_DESIGN_SKILLS),
        ("Photography & Photo Selection Skills", PHOTO_SKILLS),
        ("Professional Presentation Skills", PRESENTATION_SKILLS),
    ]
    for title, skills_dict in all_sections:
        lines.append(f"\n## {title}\n")
        for category, skills in skills_dict.items():
            lines.append(f"### {category.replace('_', ' ')}\n")
            for skill in skills:
                lines.append(f"- {skill}")
            lines.append("")
    with open(filename, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[OK] Skills exported to '{filename}'")

def count_total_skills():
    total = 0
    for d in [GRAPHIC_DESIGN_SKILLS, PHOTO_SKILLS, PRESENTATION_SKILLS]:
        for skills in d.values():
            total += len(skills)
    return total

# ─────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("\n" + "#" * 65)
    print("  DESIGN SKILLS MASTER GUIDE")
    print("  Source: Claude AI + GitHub Roadmap Research")
    print("  Repo: github.com/badrburshaid-netizen/design-skills-claude")
    print("  Generated:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    print("#" * 65)

    print_section("Graphic Design Skills", GRAPHIC_DESIGN_SKILLS, "[DESIGN]")
    print_section("Photography & Photo Selection Skills", PHOTO_SKILLS, "[PHOTO]")
    print_section("Professional Presentation Skills", PRESENTATION_SKILLS, "[SLIDES]")

    print(f"\n\n{'=' * 65}")
    print(f"  TOTAL SKILLS CATALOGUED: {count_total_skills()}")
    print(f"{'=' * 65}")

    export_to_json("design_skills.json")
    export_to_txt("design_skills.txt")
    export_to_markdown("SKILLS.md")

    print("\n[DONE] Run this script to view and export all design skills.\n")
